version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: nicaea_heroes
      POSTGRES_USER: nicaea_admin
      POSTGRES_PASSWORD: secure_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - nicaea_network
    restart: unless-stopped

  # Application
  app:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://nicaea_admin:secure_password_123@postgres:5432/nicaea_heroes
      SESSION_SECRET: super-secure-session-secret-key-change-this
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - nicaea_network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # Redis for sessions (optional, for better performance)
  redis:
    image: redis:7-alpine
    networks:
      - nicaea_network
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  nicaea_network:
    driver: bridge